version: '3'

networks:
  local-dev-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

services:
  app:
    build:
      context: .
      dockerfile: Laravel.Dockerfile
    container_name: laravel-app
    ports:
      - "8082:80"
    volumes:
      - ./Laravel-Project:/var/www/html/Laravel-Project
    depends_on:
      - database
    networks:
      - local-dev-network

  database:
    image: mysql:8.0
    container_name: database
    ports:
      - "8081:3306"
    environment:
      MYSQL_DATABASE: LaravelTest_DB
      MYSQL_ROOT_PASSWORD: DbP@ssW0Rd!
    networks:
      - local-dev-network

  vue-app:
    build:
      context: .
      dockerfile: Vue.Dockerfile
    container_name: vue-app
    ports:
      - "8080:80"
    volumes:
      - ./vue-project:/app
    networks:
      - local-dev-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8083:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - vue-app
    networks:
      - local-dev-network